"""clientes y citas

Revision ID: 0a22d14b95dd
Revises: 505ff48a1983
Create Date: 2026-09-04 01:03:40.968708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a22d14b95dd'
down_revision: Union[str, Sequence[str], None] = '505ff48a1983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_user_id'), ['user_id'], unique=False)

    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('hecha', sa.Boolean(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_citas_cliente_id_clientes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citas'))
    )
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_citas_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_apuntes_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_apuntes_cliente_id_clientes'), 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_apuntes_cliente_id_clientes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_apuntes_cliente_id'))
        batch_op.drop_column('cliente_id')

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citas_user_id'))
        batch_op.drop_index(batch_op.f('ix_citas_fecha'))
        batch_op.drop_index(batch_op.f('ix_citas_cliente_id'))

    op.drop_table('citas')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_user_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_nombre'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
