"""citas de varios dias

Una reforma de tres dias es UNA cita, no tres sueltas. `fecha_fin` va
vacia en todo lo que ya habia, que es justo lo que significa: empieza y
acaba el mismo dia.

Revision ID: 14647e9f195c
Revises: 0a22d14b95dd
Create Date: 2026-09-10 20:05:52.920663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14647e9f195c'
down_revision: Union[str, Sequence[str], None] = '0a22d14b95dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_citas_fecha_fin'), ['fecha_fin'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citas_fecha_fin'))
        batch_op.drop_column('fecha_fin')

    # ### end Alembic commands ###
