"""notas hechas

Marcar una nota cumplida en vez de borrarla. El server_default a 0 es lo
que deja pasar la columna sobre las filas que ya existen: sin el, anadir
una columna NOT NULL a una tabla con datos no cuela.

Revision ID: 203a667bf416
Revises: 14647e9f195c
Create Date: 2026-09-10 23:41:08.690195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203a667bf416'
down_revision: Union[str, Sequence[str], None] = '14647e9f195c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hecha', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.drop_column('hecha')

    # ### end Alembic commands ###
