"""esquema inicial

Revision ID: 505ff48a1983
Revises: 
Create Date: 2026-09-04 01:03:39.900840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505ff48a1983'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ajustes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('avisos_activos', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ajustes'))
    )
    with op.batch_alter_table('ajustes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ajustes_user_id'), ['user_id'], unique=True)

    op.create_table('apuntes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('pendiente', sa.Boolean(), nullable=False),
    sa.Column('origen', sa.String(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apuntes'))
    )
    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apuntes_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_apuntes_user_id'), ['user_id'], unique=False)

    op.create_table('tokens_acceso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens_acceso'))
    )
    with op.batch_alter_table('tokens_acceso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_acceso_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_acceso_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens_acceso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_acceso_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_acceso_token'))

    op.drop_table('tokens_acceso')
    with op.batch_alter_table('apuntes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apuntes_user_id'))
        batch_op.drop_index(batch_op.f('ix_apuntes_fecha'))

    op.drop_table('apuntes')
    with op.batch_alter_table('ajustes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ajustes_user_id'))

    op.drop_table('ajustes')
    # ### end Alembic commands ###
