"""habitos

Dos tablas nuevas y nada que tocar en las que ya hay. Cada dia cumplido es
una fila en habitos_hechos, unica por habito y dia: marcar dos veces el
mismo dia no puede contar doble en la racha. El dia que no se hizo no tiene
fila.

Revision ID: a65c13d5dc18
Revises: 203a667bf416
Create Date: 2026-09-13 01:56:40.846646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65c13d5dc18'
down_revision: Union[str, Sequence[str], None] = '203a667bf416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('dias', sa.String(), nullable=False),
    sa.Column('inicio', sa.Date(), nullable=False),
    sa.Column('recordar_a', sa.Time(), nullable=True),
    sa.Column('recordado_el', sa.Date(), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitos'))
    )
    with op.batch_alter_table('habitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitos_user_id'), ['user_id'], unique=False)

    op.create_table('habitos_hechos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habito_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['habito_id'], ['habitos.id'], name=op.f('fk_habitos_hechos_habito_id_habitos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habitos_hechos')),
    sa.UniqueConstraint('habito_id', 'fecha', name=op.f('uq_habitos_hechos_habito_id'))
    )
    with op.batch_alter_table('habitos_hechos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habitos_hechos_habito_id'), ['habito_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitos_hechos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habitos_hechos_habito_id'))

    op.drop_table('habitos_hechos')
    with op.batch_alter_table('habitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habitos_user_id'))

    op.drop_table('habitos')
    # ### end Alembic commands ###
